
stages:
  - prepare
  - test
  - build
  - deploy

image: node:10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ./node_modules/

install:
  stage: prepare
  tags:
    - docker
  script:
    - yarn

lint:critical:
  stage: test
  tags:
    - docker
  before_script:
    - ./dev-start.sh
  script:
    - yarn lint:critical

lint:
  stage: test
  tags:
    - docker
  before_script:
    - ./dev-start.sh
  script:
    - yarn lint
  allow_failure: true

test:
  stage: test
  tags:
    - docker
  before_script:
    - ./dev-start.sh
  script:
    - yarn test
  allow_failure: true

build:android:debug:
  stage: build
  tags:
    - android
    - node
    - react-native
  before_script:
    - ./dev-start.sh
  script:
    - ./scripts/build-android-debug.sh
  artifacts:
    paths:
      - ./build/app-debug.apk
  cache:
    key: ${CI_COMMIT_REF_SLUG}-android-ios
    paths:
      - ./node_modules/
      - ./android/.gradle/

appetize:android:debug:
  stage: deploy
  dependencies:
    - build:android:debug
  when: always
  cache: {}
  # only:
  #   - develop
  tags:
    - docker
  image: emiketic/essentials
  script:
    - ./scripts/appetize.sh ./build/app-debug.apk android

upload:android:debug:
  stage: deploy
  dependencies:
    - build:android:debug
  when: always
  cache: {}
  # only:
  #   - develop
  tags:
    - docker
  image: emiketic/essentials
  script:
    - ./scripts/deploy.sh ./build/app-debug.apk

# android:release:build:
#   stage: build
#   tags:
#     - android
#     - node
#     - react-native
#   only:
#     - master
#   before_script:
#     - yarn
#   script:
#     - ./scripts/build-android-release.sh
#     - ./scripts/deploy.sh ./build/app-release.apk
#   artifacts:
#     paths:
#       - ./build/app-release.apk

build:ios:debug:
  stage: build
  tags:
    - ios
    - node
    - react-native
  before_script:
    - ./dev-start.sh
  script:
    - ./scripts/build-ios-debug.sh
  artifacts:
    paths:
      - ./build/app-debug.zip
  cache:
    key: ${CI_COMMIT_REF_SLUG}-ios
    paths:
      - ./node_modules/
      - ./ios/Pods/

appetize:ios:debug:
  stage: deploy
  dependencies:
    - build:ios:debug
  when: always
  cache: {}
  # only:
  #   - develop
  tags:
    - docker
  image: emiketic/essentials
  script:
    - ./scripts/appetize.sh ./build/app-debug.zip ios

upload:ios:debug:
  stage: deploy
  dependencies:
    - build:ios:debug
  when: always
  cache: {}
  # only:
  #   - develop
  tags:
    - docker
  image: emiketic/essentials
  script:
    - ./scripts/deploy.sh ./build/app-debug.zip

# build:ios:release:
#   stage: build
#   tags:
#     - ios
#     - node
#     - react-native
#   only:
#     - master
#   before_script:
#     - yarn
#   script:
#     - ./scripts/build-ios-release.sh
#     - ./scripts/deploy.sh ./build/app-release.zip
#   artifacts:
#     paths:
#       - ./build/app-release.zip
